Added support for hash:ip,mark and hash:mac type of sets. Fix: some missing shift operations. Small optimizations in ipset functions.

diff --git a/ip-array_ipset_functions b/ip-array_ipset_functions
--- a/ip-array_ipset_functions
+++ b/ip-array_ipset_functions
@@ -136,7 +136,7 @@ case "$str_type" in
 		while (($#)); do
 			option="$1" opt_arg="$2"
 			if [[ -z $opt_arg ]]; then
-				log -E "$strERR Missing value to option \`$option' for \`$str_type' set." 
+				log -E "$strERR Missing value to option \`$option' for \`$str_type' set."
 				$str_failcmd
 			fi
 			case "$option" in
@@ -151,7 +151,6 @@ case "$str_type" in
 					else
 						val_ip4_addr "$opt_arg" || $str_failcmd
 					fi
-					shift 2
 				;;
 				netmask)
 					if [[ $str_type = bitmap:ip ]]; then
@@ -160,7 +159,6 @@ case "$str_type" in
 							log -E "$strERR Invalid value \`$opt_arg' with \`$option' for \`$str_type' set. Valid range: 1-32."
 							$str_failcmd
 						}
-						shift 2
 					else
 						log -E "$strERR Invalid option \`$option' for \`$str_type' set."
 						$str_failcmd
@@ -169,45 +167,66 @@ case "$str_type" in
 				;;
 				timeout)
 					val_numeric "$opt_arg" || $str_failcmd
-					shift 2
 				;;
 				*) log -E "$strERR Invalid option \`$option' for \`$str_type' set."
 					$str_failcmd
 				;;
 			esac
+			shift 2
 		done
 	;;
-	hash:ip|hash:net|hash:ip,port|hash:net,port|hash:ip,port,ip|hash:ip,port,net|hash:net,iface|hash:net,port,net)
+	hash:ip|hash:net|hash:ip,port|hash:net,port|hash:ip,port,ip|hash:ip,port,net|hash:net,iface|hash:net,port,net|hash:ip,mark|hash:mac)
 		local -a arr_opts=("$@")
 		while (($#)); do
 			option="$1" opt_arg="$2"
-			if [[ -z $opt_arg ]]; then
-				log -E "$strERR Missing value to option \`$option' for \`$str_type' set." 
-				$str_failcmd
+			if [[ $option = @(family|maxelem|hashsize|timeout|markmask) ]]; then
+				if [[ -z $opt_arg ]]; then
+					log -E "$strERR Missing value to option \`$option' for \`$str_type' set."
+					$str_failcmd
+				fi
+			fi
+			if [[ $option = @(comment|counters|markmask|skbinfo) ]]; then
+				if ((IPSET_VERSION[0] < 6)); then
+					log -E "Option \`$option' is not supported: ipset version is too old."
+					$str_failcmd
+				fi
 			fi
 			case "$option" in
-				comment)
-					# ipset -ge v6.20 has comment flag
-					if ((IPSET_VERSION[0] < 6)); then
+				markmask)
+					# ipset -ge v6.21 has markmask flag
+					if ((IPSET_VERSION[0] == 6 && IPSET_VERSION[1] < 21)); then
 						log -E "Option \`$option' is not supported: ipset version is too old."
 						$str_failcmd
-					else
-						if ((IPSET_VERSION[0] == 6 && IPSET_VERSION[1] < 20)); then
-							log -E "Option \`$option' is not supported: ipset version is too old."
-							$str_failcmd
-						fi
+					fi
+					if [[ $str_type != hash:ip,mark ]]; then
+						log -E "Option  \`$option' is only available for hash:ip,mark type of sets."
+						$str_failcmd
+					fi
+					val_32bit_off1 "$opt_arg" || {
+						log -E "$strERR Value \`$opt_arg' is not valid for the markmask option must be between 1 and 4294967295."
+						$str_failcmd
+					}
+					shift
+				;;
+				skbinfo)
+					# ipset -ge v6.22 has skbinfo flag
+					if ((IPSET_VERSION[0] == 6 && IPSET_VERSION[1] < 22)); then
+						log -E "Option \`$option' is not supported: ipset version is too old."
+						$str_failcmd
+					fi
+				;;
+				comment)
+					# ipset -ge v6.20 has comment flag
+					if ((IPSET_VERSION[0] == 6 && IPSET_VERSION[1] < 20)); then
+						log -E "Option \`$option' is not supported: ipset version is too old."
+						$str_failcmd
 					fi
 				;;
 				counters)
 					# ipset -ge v6.19 has counters flag
-					if ((IPSET_VERSION[0] < 6)); then
+					if ((IPSET_VERSION[0] == 6 && IPSET_VERSION[1] < 19)); then
 						log -E "Option \`$option' is not supported: ipset version is too old."
 						$str_failcmd
-					else
-						if ((IPSET_VERSION[0] == 6 && IPSET_VERSION[1] < 19)); then
-							log -E "Option \`$option' is not supported: ipset version is too old."
-							$str_failcmd
-						fi
 					fi
 				;;
 				family)
@@ -218,16 +237,20 @@ case "$str_type" in
 					else
 						log -E "$strERR Invalid value \`$opt_arg' with \`$option' for \`$str_type' set. Valid values: inet|inet6."
 						$str_failcmd
-					fi	
-					shift 2
+					fi
+					if [[ $str_type = hash:mac ]]; then
+						log -E "$strERR Option  \`$option' is not available for hash:mac type of sets."
+						$str_failcmd
+					fi
+					shift
 				;;
 				hashsize)
 					val_numeric "$opt_arg" || $str_failcmd
-					shift 2
+					shift
 				;;
 				maxelem)
 					val_numeric "$opt_arg" || $str_failcmd
-					shift 2
+					shift
 				;;
 				netmask)
 					case "$str_type" in
@@ -236,19 +259,20 @@ case "$str_type" in
 								log -E "$strERR Invalid value \`$opt_arg' with \`$option' for \`$str_type' set. Valid range: 1-32."
 								$str_failcmd
 							}
-							shift 2
 						;;
 						*) log -E "$strERR Invalid option \`$option' for \`$str_type' set."
 							$str_failcmd
 					esac
+					shift
 				;;
 				timeout)
 					val_numeric "$opt_arg" || $str_failcmd
-					shift 2
+					shift
 				;;
 				*) log -E "$strERR Invalid option \`$option' for \`$str_type' set."
 					$str_failcmd
 			esac
+			shift
 		done
 	;;
 	list:set)
@@ -256,21 +280,20 @@ case "$str_type" in
 		while (($#)); do
 			option="$1" opt_arg="$2"
 			if [[ -z $opt_arg ]]; then
-				log -E "$strERR Missing value to option \`$option' for \`$str_type' set." 
+				log -E "$strERR Missing value to option \`$option' for \`$str_type' set."
 				$str_failcmd
 			fi
 			case "$option" in
 				size)
 					val_numeric "$opt_arg" || $str_failcmd
-					shift 2
 				;;
 				timeout)
 					val_numeric "$opt_arg" || $str_failcmd
-					shift 2
 				;;
 				*) log -E "$strERR Invalid option \`$option' for \`$str_type' set."
 					$str_failcmd
 			esac
+			shift 2
 		done
 	;;
 	ipmap)
@@ -278,24 +301,21 @@ case "$str_type" in
 		while (($#)); do
 			option="$1" opt_arg="$2"
 			if [[ -z $opt_arg ]]; then
-				log -E "$strERR Missing value to option \`$option' for \`$str_type' set." 
+				log -E "$strERR Missing value to option \`$option' for \`$str_type' set."
 				$str_failcmd
 			fi
 			case "$option" in
 				from)
 					val_ip4_ip "$opt_arg" || $str_failcmd
 					str_from="--$option $opt_arg"
-					shift 2
 				;;
 				to)
 					val_ip4_ip "$opt_arg" || $str_failcmd
 					str_to="--$option $opt_arg"
-					shift 2
 				;;
 				network)
 					val_ip4_cidr_net "$opt_arg" || $str_failcmd
 					str_network="--$option $opt_arg"
-					shift 2
 				;;
 				netmask)
 					((opt_arg >= 1 && <= 31)) || {
@@ -303,13 +323,13 @@ case "$str_type" in
 						$str_failcmd
 					}
 					str_netmask="--$option $opt_arg"
-					shift 2
 				;;
 				*) log -E "$strERR Invalid option \`$option' for \`$str_type' set."
 					$str_failcmd
 			esac
+			shift 2
 		done
-		if [[ $str_network ]]; then 
+		if [[ $str_network ]]; then
 			if [[ $str_netmask ]]; then arr_opts=($str_network $str_netmask)
 			else arr_opts=($str_network)
 			fi
@@ -336,7 +356,7 @@ case "$str_type" in
 			case "$option" in
 				from|to|network)
 					if [[ -z $opt_arg ]]; then
-						log -E "$strERR Missing value to option \`$option' for \`$str_type' set." 
+						log -E "$strERR Missing value to option \`$option' for \`$str_type' set."
 						$str_failcmd
 					fi
 				;;
@@ -345,25 +365,25 @@ case "$str_type" in
 				from)
 					val_ip4_ip "$opt_arg" || $str_failcmd
 					str_from="--$option $opt_arg"
-					shift 2
+					shift
 				;;
 				to)
 					val_ip4_ip "$opt_arg" || $str_failcmd
 					str_to="--$option $opt_arg"
-					shift 2
+					shift
 				;;
 				network)
 					val_ip4_cidr_net "$opt_arg" || $str_failcmd
 					arr_opts=(--$option $opt_arg)
-					shift 2
+					shift
 				;;
 				matchunset)
 					arr_opts[${#arr_opts[@]}]="--$option"
-					shift
 				;;
 				*) log -E "$strERR Invalid option \`$option' for \`$str_type' set."
 					$str_failcmd
 			esac
+			shift
 		done
 		if [[ $str_from && $str_to ]]; then
 			arr_opts=($str_from $str_to)
@@ -395,12 +415,10 @@ case "$str_type" in
 				hashsize|probes)
 					val_numeric "$opt_arg" || $str_failcmd
 					arr_opts[${#arr_opts[@]}]="--$option $opt_arg"
-					shift 2
 				;;
 				resize)
 					val_numeric "$opt_arg" || $str_failcmd
 					arr_opts[${#arr_opts[@]}]="--$option $opt_arg"
-					shift 2
 				;;
 				netmask)
 					((opt_arg >= 1 && <= 31)) || {
@@ -408,34 +426,33 @@ case "$str_type" in
 						$str_failcmd
 					}
 					arr_opts[${#arr_opts[@]}]="--$option $opt_arg"
-					shift 2
 				;;
 				*) log -E "$strERR Invalid option \`$option' for \`$str_type' set."
 					$str_failcmd
 			esac
+			shift 2
 		done
 	;;
 	nethash)
 		while (($#)); do
 			option="$1" opt_arg="$2"
 			if [[ -z $opt_arg ]]; then
-				log -E "$strERR Missing value to option \`$option' for \`$str_type' set." 
+				log -E "$strERR Missing value to option \`$option' for \`$str_type' set."
 				$str_failcmd
 			fi
 			case "$option" in
 				hashsize|probes)
 					val_numeric "$opt_arg" || $str_failcmd
 					arr_opts[${#arr_opts[@]}]="--$option $opt_arg"
-					shift 2
 				;;
 				resize)
 					val_numeric "$opt_arg" || $str_failcmd
 					arr_opts[${#arr_opts[@]}]="--$option $opt_arg"
-					shift 2
 				;;
 				*) log -E "$strERR Invalid option \`$option' for \`$str_type' set."
 					$str_failcmd
 			esac
+			shift 2
 		done
 	;;
 	ipporthash|ipportiphash|ipportnethash)
@@ -443,38 +460,34 @@ case "$str_type" in
 		while (($#)); do
 			option="$1" opt_arg="$2"
 			if [[ -z $opt_arg ]]; then
-				log -E "$strERR Missing value to option \`$option' for \`$str_type' set." 
+				log -E "$strERR Missing value to option \`$option' for \`$str_type' set."
 				$str_failcmd
 			fi
 			case "$option" in
 				from)
 					val_ip4_ip "$opt_arg" || $str_failcmd
 					str_from="--$option $opt_arg"
-					shift 2
 				;;
 				to)
 					val_ip4_ip "$opt_arg" || $str_failcmd
 					str_to="--$option $opt_arg"
-					shift 2
 				;;
 				network)
 					val_ip4_cidr_net "$opt_arg" || $str_failcmd
 					arr_opts[${#arr_opts[@]}]="--$option $opt_arg"
-					shift 2
 				;;
 				hashsize|probes)
 					val_numeric "$opt_arg" || $str_failcmd
 					arr_opts[${#arr_opts[@]}]="--$option $opt_arg"
-					shift 2
 				;;
 				resize)
 					val_numeric "$opt_arg" || $str_failcmd
 					arr_opts[${#arr_opts[@]}]="--$option $opt_arg"
-					shift 2
 				;;
 				*) log -E "$strERR Invalid option \`$option' for \`$str_type' set."
 					$str_failcmd
 			esac
+			shift 2
 		done
 		if [[ $str_from && $str_to ]]; then
 			arr_opts[${#arr_opts[@]}]="$str_from $str_to"
@@ -555,10 +568,6 @@ case $str_type in
 			*-*|\[*\]-\[*\]) val_port_range_word "$str_in" || $str_failcmd ;;
 			*) val_port "$str_in" || $str_failcmd
 		esac
-	;;
-	hash:net,iface)
-		val_ip4_cidr_net "${str_in%,*}" || $str_failcmd
-		check_iface "${str_in#*,}" || $str_failcmd
 	;;
 	iptree)
 		case "$str_in" in
@@ -653,6 +662,17 @@ case $str_type in
 				$str_failcmd
 		esac
 	;;
+	hash:net,iface)
+		val_ip4_cidr_net "${str_in%,*}" || $str_failcmd
+		check_iface "${str_in#*,}" || $str_failcmd
+	;;
+	hash:ip,mark)
+		val_ip4_ip "${str_in%,*}" || $str_failcmd
+		val_32bit "${str_in#*,}" || $str_failcmd
+	;;
+	hash:mac)
+		val_mac "$str_in" || $str_failcmd
+	;;
 	setlist|list:set)
 		case "$str_in" in
 			*,@(before|after),*)
@@ -682,31 +702,36 @@ while (($#)); do # remaining options
 	option="$1" opt_arg="$2"
 	shift
 	if [[ $IPSET_SYNTAX = new ]]; then
+		if [[ $option = @(bytes|packets|comment|nomatch|skbmark|skbprio|skbqueue) ]]; then
+			if ((IPSET_VERSION[0] < 6)); then
+				log -E "Option \`$option' is not supported: ipset version is too old."
+				$str_failcmd
+			fi
+		fi
 		case "$option" in
 			comment)
 				# ipset -ge v6.20 has comment flag
-				if ((IPSET_VERSION[0] < 6)); then
+				if ((IPSET_VERSION[0] == 6 && IPSET_VERSION[1] < 20)); then
 					log -E "Option \`$option' is not supported: ipset version is too old."
 					$str_failcmd
-				else
-					if ((IPSET_VERSION[0] == 6 && IPSET_VERSION[1] < 20)); then
-						log -E "Option \`$option' is not supported: ipset version is too old."
-						$str_failcmd
-					fi
 				fi
+				shift
 			;;
 			bytes|packets)
 				# ipset -ge v6.19 has counters flag
-				if ((IPSET_VERSION[0] < 6)); then
+				if ((IPSET_VERSION[0] == 6 && IPSET_VERSION[1] < 19)); then
 					log -E "Option \`$option' is not supported: ipset version is too old."
 					$str_failcmd
-				else
-					if ((IPSET_VERSION[0] == 6 && IPSET_VERSION[1] < 19)); then
-						log -E "Option \`$option' is not supported: ipset version is too old."
-						$str_failcmd
-					fi
 				fi
 				val_numeric "$opt_arg" || $str_failcmd
+				shift
+			;;
+			skbmark|skbprio|skbqueue)
+				# ipset -ge v6.22 has comment flag
+				if ((IPSET_VERSION[0] == 6 && IPSET_VERSION[1] < 22)); then
+					log -E "Option \`$option' is not supported: ipset version is too old."
+					$str_failcmd
+				fi
 				shift
 			;;
 			timeout)
@@ -737,7 +762,7 @@ while (($#)); do # remaining options
 	else
 		case "$option" in
 			-q|--quiet) : ;;
-			quiet) 
+			quiet)
 				for opt_arg in ${!arr_opts[@]}; do
 					if [[ ${arr_opts[opt_arg]} = quiet ]]; then
 						arr_opts[opt_arg]=--quiet
