Added support for the IDLETIMER target.

diff --git a/ip-array_ipt_functions b/ip-array_ipt_functions
--- a/ip-array_ipt_functions
+++ b/ip-array_ipt_functions
@@ -1362,12 +1362,12 @@ val_32bit "$1" || {
 }
 } # -------------------------------------------------------------------------
 
-val_rt_realm() { # validata a named routing realm
+val_rt_realm() { # validate a named routing realm
 local -i i
 for i in ${!RT_REALMS_ARRAY[@]}; do
 	[[ $1 = ${RT_REALMS_ARRAY[i]} ]] && return
 done
-log -E "Cannot find named routing realm \`$1'"
+log -E "Cannot find named routing realm \`$1'."
 return 1
 } # -------------------------------------------------------------------------
 
@@ -3901,6 +3901,7 @@ case "$str_target" in
 	DROP) str_target_msg="drop" ;;
 	ECN) str_target_msg="remove-ecn" ;;
 	CHECKSUM) str_target_msg="fill-checksum" ;;
+	IDLETIMER) str_target_msg="idletimer" ;;
 	LOG) str_target_msg="log" ;;
 	NFLOG) str_target_msg="nflog" ;;
 	ULOG) str_target_msg="ulog" ;;
@@ -4522,6 +4523,29 @@ esac
 _process_comment() {
 RULELIST_COMMENT[RULE_LIST_IDX]="-m comment --comment \"${arg_list_comment[ARG_LIST_IDX]}\" "
 MSG_LIST_COMMENT[RULE_LIST_IDX]="comment='${arg_list_comment[ARG_LIST_IDX]}' "
+} # -------------------------------------------------------------------------
+
+_process_idletimer_opt() { # fill the idletimer target rulelist and msglist arrays
+local str_ilabel str_itmout
+case "${arg_list_idletimer_opt[ARG_LIST_IDX]}" in
+	label:*:timeout:+([[:digit:]])|timeout:+([[:digit:]]):label:*)
+		case "${arg_list_idletimer_opt[ARG_LIST_IDX]}" in
+			label:*:timeout:+([[:digit:]]))
+				str_ilabel="${arg_list_idletimer_opt[ARG_LIST_IDX]%:timeout:*}"
+				str_ilabel="${str_ilabel#label:}"
+				str_itmout="${arg_list_idletimer_opt[ARG_LIST_IDX]#*:timeout:}"
+			;;
+			timeout:+([[:digit:]]):label:*)
+				str_ilabel="${arg_list_idletimer_opt[ARG_LIST_IDX]#*:label:}"
+				str_itmout="${arg_list_idletimer_opt[ARG_LIST_IDX]%:label:*}"
+				str_itmout="${str_itmout#timeout:}"
+			;;
+		esac
+	;;
+	*) log -U $FUNCNAME; return 1
+esac
+RULELIST_IDLETIMER_OPT[RULE_LIST_IDX]="--label \"$str_ilabel\" --timeout $str_itmout"
+MSG_LIST_IDLETIMER_OPT[RULE_LIST_IDX]="idletimer_label='$str_ilabel' idletimer_timeout=$str_itmout"
 } # -------------------------------------------------------------------------
 
 _process_t_dscp() { # fill the dscp target rulelist and msglist arrays
@@ -5720,6 +5744,32 @@ for pos_idx in ${!tmp_pos_par_val_array[@]}; do
 				log -i "$tmp_opt_var_value" "socket descriptor"
 				return 1
 			fi
+		;;
+		(idletimer_opt)
+			((IDLETIMER_TGT_EXIST)) || { log -t 'IDLETIMER'; return 1; }
+			case "$tmp_opt_var_value" in
+				label:*:timeout:+([[:digit:]])|timeout:+([[:digit:]]):label:*)
+					case "$tmp_opt_var_value" in
+						label:*:timeout:+([[:digit:]]))
+							local str_ilabel="${tmp_opt_var_value%:timeout:*}"
+							local str_ilabel="${str_ilabel#label:}"
+							local str_itmout="${tmp_opt_var_value#*:timeout:}"
+						;;
+						timeout:+([[:digit:]]):label:*)
+							local str_ilabel="${tmp_opt_var_value#*:label:}"
+							local str_itmout="${tmp_opt_var_value%:label:*}"
+							local str_itmout="${str_itmout#timeout:}"
+						;;
+					esac
+					val_numeric "$str_itmout" || return 1
+					((${#str_ilabel} <= 27)) || {
+						log -E "IDLETIMER label must not exceed 27 characters."
+						return 1
+					}
+				;;
+				*) log -i "$tmp_opt_var_value" "IDLETIMER value descriptor"
+					return 1
+			esac
 		;;
 		(t_mark)
 			((MARK_TGT_EXIST)) || { log -t 'MARK'; return 1; }
