Moved all NAT options into one ipt_arg named nat_opt.

diff --git a/ip-array_ipt_functions b/ip-array_ipt_functions
--- a/ip-array_ipt_functions
+++ b/ip-array_ipt_functions
@@ -4108,55 +4108,86 @@ case "${arg_list_t_connsecmark[ARG_LIST_IDX]}" in
 esac
 } # -------------------------------------------------------------------------
 
-_process_nat_ip() { # fill the nat ip address rulelist and msglist arrays
-case "$str_target" in
-	SNAT)
-		RULELIST_NAT_IP[RULE_LIST_IDX]="--to-source ${arg_list_nat_ip[ARG_LIST_IDX]}"
-		MSG_LIST_NAT_IP[RULE_LIST_IDX]="NATsrc=${arg_list_nat_ip[ARG_LIST_IDX]} "
-	;;
-	DNAT)
-		RULELIST_NAT_IP[RULE_LIST_IDX]="--to-destination ${arg_list_nat_ip[ARG_LIST_IDX]}"
-		MSG_LIST_NAT_IP[RULE_LIST_IDX]="NATdst=${arg_list_nat_ip[ARG_LIST_IDX]} "
-	;;
-	NETMAP)
-		RULELIST_NAT_IP[RULE_LIST_IDX]="--to ${arg_list_nat_ip[ARG_LIST_IDX]}"
-		MSG_LIST_NAT_IP[RULE_LIST_IDX]="NATdst=${arg_list_nat_ip[ARG_LIST_IDX]} "
-	;;
-	RAWSNAT)
-		RULELIST_NAT_IP[RULE_LIST_IDX]="--to-source ${arg_list_nat_ip[ARG_LIST_IDX]}"
-		MSG_LIST_NAT_IP[RULE_LIST_IDX]="NATsrc=${arg_list_nat_ip[ARG_LIST_IDX]} "
-	;;
-	RAWDNAT)
-		RULELIST_NAT_IP[RULE_LIST_IDX]="--to-destination ${arg_list_nat_ip[ARG_LIST_IDX]}"
-		MSG_LIST_NAT_IP[RULE_LIST_IDX]="NATdst=${arg_list_nat_ip[ARG_LIST_IDX]} "
-	;;
-	*) log -i "$str_target" 'an iptables target'
-		return 1
-esac
-} # -------------------------------------------------------------------------
+#_process_nat_ip() { # fill the nat ip address rulelist and msglist arrays
+#case "$str_target" in
+#	SNAT)
+#		RULELIST_NAT_IP[RULE_LIST_IDX]="--to-source ${arg_list_nat_ip[ARG_LIST_IDX]}"
+#		MSG_LIST_NAT_IP[RULE_LIST_IDX]="NATsrc=${arg_list_nat_ip[ARG_LIST_IDX]} "
+#	;;
+#	DNAT)
+#		RULELIST_NAT_IP[RULE_LIST_IDX]="--to-destination ${arg_list_nat_ip[ARG_LIST_IDX]}"
+#		MSG_LIST_NAT_IP[RULE_LIST_IDX]="NATdst=${arg_list_nat_ip[ARG_LIST_IDX]} "
+#	;;
+#	NETMAP)
+#		RULELIST_NAT_IP[RULE_LIST_IDX]="--to ${arg_list_nat_ip[ARG_LIST_IDX]}"
+#		MSG_LIST_NAT_IP[RULE_LIST_IDX]="NATdst=${arg_list_nat_ip[ARG_LIST_IDX]} "
+#	;;
+#	RAWSNAT)
+#		RULELIST_NAT_IP[RULE_LIST_IDX]="--to-source ${arg_list_nat_ip[ARG_LIST_IDX]}"
+#		MSG_LIST_NAT_IP[RULE_LIST_IDX]="NATsrc=${arg_list_nat_ip[ARG_LIST_IDX]} "
+#	;;
+#	RAWDNAT)
+#		RULELIST_NAT_IP[RULE_LIST_IDX]="--to-destination ${arg_list_nat_ip[ARG_LIST_IDX]}"
+#		MSG_LIST_NAT_IP[RULE_LIST_IDX]="NATdst=${arg_list_nat_ip[ARG_LIST_IDX]} "
+#	;;
+#	*) log -i "$str_target" 'an iptables target'
+#		return 1
+#esac
+#} # -------------------------------------------------------------------------
+#
+#_process_nat_port() { # fill the nat port address rulelist and msglist arrays
+#case "$str_target" in
+#	MASQUERADE|REDIRECT)
+#		case "$(string_tolower "${arg_list_proto[ARG_LIST_IDX]:-0}")" in # only valid with tcp or udp
+#			(tcp|udp|6|17)
+#				RULELIST_NAT_PORT[RULE_LIST_IDX]="--to-ports ${arg_list_nat_port[ARG_LIST_IDX]/:/} "
+#			;;
+#		esac
+#	;;
+#	*) RULELIST_NAT_PORT[RULE_LIST_IDX]=":${arg_list_nat_port[ARG_LIST_IDX]} "
+#esac
+#MSG_LIST_NAT_PORT[RULE_LIST_IDX]="NATport=${arg_list_nat_port[ARG_LIST_IDX]} "
+#} # -------------------------------------------------------------------------
 
-_process_nat_port() { # fill the nat port address rulelist and msglist arrays
-case "$str_target" in
-	MASQUERADE|REDIRECT)
-		case "$(string_tolower "${arg_list_proto[ARG_LIST_IDX]:-0}")" in # only valid with tcp or udp
-			(tcp|udp|6|17)
-				RULELIST_NAT_PORT[RULE_LIST_IDX]="--to-ports ${arg_list_nat_port[ARG_LIST_IDX]/:/} "
-			;;
-		esac
-	;;
-	*) RULELIST_NAT_PORT[RULE_LIST_IDX]=":${arg_list_nat_port[ARG_LIST_IDX]} "
-esac
-MSG_LIST_NAT_PORT[RULE_LIST_IDX]="NATport=${arg_list_nat_port[ARG_LIST_IDX]} "
-} # -------------------------------------------------------------------------
-
-_process_nat_option() {
-case "${arg_list_nat_option[ARG_LIST_IDX]}" in
-	random|persistent)
-		RULELIST_NAT_OPTION[RULE_LIST_IDX]="--${arg_list_nat_option[ARG_LIST_IDX]}"
-		MSG_LIST_NAT_OPTION[RULE_LIST_IDX]="NAToption=${arg_list_nat_option[ARG_LIST_IDX]}"
-	;;
-	*) log -U $FUNCNAME; return 1
-esac
+_process_nat_opt() {
+local str_opts="" str_addr="" str_p=""
+set -- $(split_val : ' ' "${arg_list_nat_opt[ARG_LIST_IDX]}")
+while (($#)); do
+	case "$1" in
+		addr) str_opts+="--to-address $2 "
+			shift
+		;;
+		daddr) str_addr+="--to-destination $2"
+			shift
+		;;
+		saddr) str_addr+="--to-source $2"
+			shift
+		;;
+		port) str_p="$2"
+			shift
+		;;
+		random|persistent|random-fully) str_opts+="--$1 "
+		;;
+		*) log -U $FUNCNAME; return 1
+	esac
+	shift
+done
+if [[ $str_p && $str_addr ]]; then
+	str_addr="${str_addr}:$str_p"
+elif [[ $str_p ]]; then
+	str_opts+="--to-ports $str_p "
+elif [[ $str_addr ]]; then
+	str_opts+="$str_addr "
+fi
+RULELIST_NAT_OPTION[RULE_LIST_IDX]="$str_opts"
+MSG_LIST_NAT_OPTION[RULE_LIST_IDX]="NAT-option=${arg_list_nat_opt[ARG_LIST_IDX]}"
+#case "${arg_list_nat_opt[ARG_LIST_IDX]}" in
+#	random|persistent)
+#		RULELIST_NAT_OPTION[RULE_LIST_IDX]="--${arg_list_nat_opt[ARG_LIST_IDX]}"
+#		MSG_LIST_NAT_OPTION[RULE_LIST_IDX]="NAToption=${arg_list_nat_opt[ARG_LIST_IDX]}"
+#	;;
+#	*) log -U $FUNCNAME; return 1
+#esac
 } # -------------------------------------------------------------------------
 
 _process_reject_type() { # fill the reject type rulelist and msglist arrays
@@ -5823,39 +5854,61 @@ for pos_idx in ${!tmp_pos_par_val_array[@]}; do
 				esac
 			done
 		;;
-		(nat_ip)
-			validate_nat_ip "$tmp_opt_var_value" || return 1
-		;;
-		(nat_port)
-			val_nat_port "$tmp_opt_var_value" || return 1
-		;;
-		(nat_option)
-			case "$tmp_opt_var_value" in
-				random)
-					if ((KERN_VER[0] == 2)); then
-						if ((KERN_VER[1] < 6)); then
-							log -E "NAT \`random' option requires kernel versions greater or equal to \`2.6.21'."
-							return 1
-						elif ((KERN_VER[1] == 6 && KERN_VER[2] < 21)); then
-							log -E "NAT \`random' option requires kernel versions greater or equal to \`2.6.21'."
-							return 1
-						fi
-					fi
-				;;
-				persistent)
-					if ((KERN_VER[0] == 2)); then
-						if ((KERN_VER[1] < 6)); then
-							log -E "NAT \`persistent' option requires kernel versions greater or equal to \`2.6.29'."
-							return 1
-						elif ((KERN_VER[1] == 6 && KERN_VER[2] < 29)); then
-							log -E "NAT \`persistent' option requires kernel versions greater or equal to \`2.6.29'."
+#		(nat_ip)
+#			validate_nat_ip "$tmp_opt_var_value" || return 1
+#		;;
+#		(nat_port)
+#			val_nat_port "$tmp_opt_var_value" || return 1
+#		;;
+		(nat_opt)
+			set -- ${tmp_opt_var_value//:/ }
+			while (($#)); do
+				case "$1" in
+					port)
+						if [[ $2 ]]; then
+							val_nat_port "$2" || return 1
+						else
+							log -E "NAT port specification is missing."
 							return 1
 						fi
-					fi
-				;;
-				*) log -i "$tmp_opt_var_value" "NAT option descriptor"
-					return 1
-			esac
+						shift
+					;;
+					addr|daddr|saddr)
+						if [[ $2 ]]; then
+							validate_nat_ip "$2" || return 1
+						else
+							log -E "NAT address specification is missing."
+							return 1
+						fi
+						shift
+					;;
+					random)
+						if ((KERN_VER[0] == 2)); then
+							if ((KERN_VER[1] < 6)); then
+								log -E "NAT \`random' option requires kernel versions greater or equal to \`2.6.21'."
+								return 1
+							elif ((KERN_VER[1] == 6 && KERN_VER[2] < 21)); then
+								log -E "NAT \`random' option requires kernel versions greater or equal to \`2.6.21'."
+								return 1
+							fi
+						fi
+					;;
+					persistent)
+						if ((KERN_VER[0] == 2)); then
+							if ((KERN_VER[1] < 6)); then
+								log -E "NAT \`persistent' option requires kernel versions greater or equal to \`2.6.29'."
+								return 1
+							elif ((KERN_VER[1] == 6 && KERN_VER[2] < 29)); then
+								log -E "NAT \`persistent' option requires kernel versions greater or equal to \`2.6.29'."
+								return 1
+							fi
+						fi
+					;;
+					*) log -i "$tmp_opt_var_value" "NAT option descriptor"
+						return 1
+				esac
+				shift
+			done
 		;;
 		(t_ttl|m_ttl)
 			case "$tmp_opt_var" in
@@ -6064,21 +6117,22 @@ for target_idx in ${!arg_list_target[@]}; do
 				_val_tgtopt_set "${arg_list_t_ttl[ARG_LIST_IDX]}" || return 1
 			;;
 			DNAT|SNAT|NETMAP)
-				check_var_no_sep_silent "${arg_list_nat_ip[ARG_LIST_IDX]}" || {
+#				check_var_no_sep_silent "${arg_list_nat_ip[ARG_LIST_IDX]}" || {
+				[[ ${arg_list_nat_opt[ARG_LIST_IDX]} = *addr:?* ]] || {
 					log -E "No $str_target target IP address specified."
 					return 1
 				}
-				if [[ ${arg_list_nat_option[ARG_LIST_IDX]} && ${arg_list_nat_option[ARG_LIST_IDX]} = @(random|persistent) && $str_target != @(DNAT|SNAT) ]]
+				if [[ ${arg_list_nat_opt[ARG_LIST_IDX]} && ${arg_list_nat_opt[ARG_LIST_IDX]} = *@(random|persistent)* && $str_target != @(DNAT|SNAT) ]]
 				then
-					log -E "\`${arg_list_nat_option[ARG_LIST_IDX]}' is not valid with $str_target target."
+					log -E "\`${arg_list_nat_opt[ARG_LIST_IDX]}' is not valid with $str_target target."
 					return 1
 				fi
 			;;
 			MASQUERADE|REDIRECT)
-				if [[ ${arg_list_nat_option[ARG_LIST_IDX]} && ${arg_list_nat_option[ARG_LIST_IDX]} != random ]]; then
-					log -E "\`${arg_list_nat_option[ARG_LIST_IDX]}' is not valid with $str_target target."
+				if [[ ${arg_list_nat_opt[ARG_LIST_IDX]} && ${arg_list_nat_opt[ARG_LIST_IDX]} = *persistent* ]]; then
+					log -E "\`persistent' is not valid with $str_target target."
 					return 1
-				else
+				elif [[ ${arg_list_nat_opt[ARG_LIST_IDX]} && ${arg_list_nat_opt[ARG_LIST_IDX]} = *random* ]]; then
 					if [[ $str_target = REDIRECT ]]; then
 						if ((KERN_VER[0] == 2)); then
 							if ((KERN_VER[1] < 6)) || ((KERN_VER[1] == 6 && KERN_VER[2] < 22)); then
@@ -6089,7 +6143,8 @@ for target_idx in ${!arg_list_target[@]}; do
 					fi
 				fi
 				
-				if [[ ${arg_list_nat_port[ARG_LIST_IDX]} ]]; then # if a nat port is defined
+#				if [[ ${arg_list_nat_port[ARG_LIST_IDX]} ]]; then # if a nat port is defined
+				if [[ ${arg_list_nat_opt[ARG_LIST_IDX]} = *port:?* ]]; then # if a nat port is defined
 					check_var_no_sep_silent "${arg_list_proto[ARG_LIST_IDX]}" || {
 						log -E "Protocol not defined, port specifications with $str_target are only valid with tcp or udp."
 						return 1
@@ -6176,7 +6231,8 @@ case "$table" in
 	nat)
 		case "$str_target" in
 			MASQUERADE|REDIRECT)
-				if [[ ${arg_list_nat_port[ARG_LIST_IDX]} ]]; then # if a nat port is defined
+#				if [[ ${arg_list_nat_port[ARG_LIST_IDX]} ]]; then # if a nat port is defined
+				if [[ ${arg_list_nat_opt[ARG_LIST_IDX]} = *port:?* ]]; then # if a nat port is defined
 					if [[ $(string_tolower "${arg_list_proto[ARG_LIST_IDX]:-0}") != @(tcp|udp|6|17) ]]; then
 						log -E "Port specifications with $str_target are only valid with tcp or udp."
 						return 1
