Added support for the realm match.

diff --git a/ip-array_ipt_functions b/ip-array_ipt_functions
--- a/ip-array_ipt_functions
+++ b/ip-array_ipt_functions
@@ -1362,6 +1362,15 @@ val_32bit "$1" || {
 }
 } # -------------------------------------------------------------------------
 
+val_rt_realm() { # validata a named routing realm
+local -i i
+for i in ${!RT_REALMS_ARRAY[@]}; do
+	[[ $1 = ${RT_REALMS_ARRAY[i]} ]] && return
+done
+log -E "Cannot find named routing realm \`$1'"
+return 1
+} # -------------------------------------------------------------------------
+
 val_dccp_types() { # validate dccp protocol  types
 [[ $1 ]] || { reqparm $FUNCNAME 1; return 1; }
 set -- $(split_val , ' ' "$1")
@@ -4486,6 +4495,13 @@ RULELIST_PKTTYPE[RULE_LIST_IDX]="-m pkttype ${str_neg}--pkt-type $(remove_negati
 MSG_LIST_PKTTYPE[RULE_LIST_IDX]="pkt-type=${arg_list_pkttype[ARG_LIST_IDX]} "
 } # -------------------------------------------------------------------------
 
+_process_realm() { # fill the realm match rulelist and msglist arrays
+local str_neg=""
+string_negated "${arg_list_realm[ARG_LIST_IDX]}" && str_neg="! "
+RULELIST_REALM[RULE_LIST_IDX]="-m realm ${str_neg}--realm $(remove_negation "${arg_list_realm[ARG_LIST_IDX]}") "
+MSG_LIST_REALM[RULE_LIST_IDX]="realm=${arg_list_realm[ARG_LIST_IDX]} "
+} # -------------------------------------------------------------------------
+
 _process_statistic() {
 local str_val str_neg=""
 string_negated "${arg_list_statistic[ARG_LIST_IDX]#*:}" && str_neg="! "
@@ -5683,6 +5699,19 @@ for pos_idx in ${!tmp_pos_par_val_array[@]}; do
 				unicast|broadcast|multicast) : ;;
 				*) log -i "$tmp_opt_var_value" "pkttype descriptor"
 					return 1
+			esac
+		;;
+		(realm)
+			((realm_MOD_EXIST)) || { log -s 'realm'; return 1; }
+			case "$tmp_opt_var_value_neg_ok" in
+				+([[:digit:]]))
+				;;
+				+([[:digit:]])/+([[:digit:]]))
+				;;
+				*) val_rt_realm "$tmp_opt_var_value_neg_ok" || {
+				   	log -i "$tmp_opt_var_value" "realm descriptor"
+					return 1
+				}
 			esac
 		;;
 		(socket)
